name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t BA-web-application:latest .

    - name: Run tests
      run: docker run --rm BA-web-application:latest npm test
      env:
        CI: true

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to registry
      if: ${{ job.status == 'success' && github.event_name == 'push' }}
      run: docker push gorm2303/BA-web-application