name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t ba-web-application:latest .

    - name: Run tests
      env:
        CI: true
      run: docker run ba-web-application:latest npm test


    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to registry
      if: ${{ job.status == 'success' && github.event_name == 'push' }}
      run: docker push gorm2303/ba-web-application