name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ba-web-application .
      
    - name: Make testable dockerfile 
      run: ./.github/workflows/make_testable_dockerfile.sh ../../Dockerfile

    - name: Build testable Docker image
      run: docker build -t testable-docker-image -f ./.github/workflows/testable_dockerfile .

    - name: Run tests
      run: docker run -e CI=true testable-docker-image npm test 

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to registry
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ba-web-application
